#ifndef CODEX_REMOTE_PROTOCOL_H
#define CODEX_REMOTE_PROTOCOL_H

#include <stddef.h>
#include <stdint.h>

#define CR_PROTOCOL_MAJOR UINT8_C(1)
#define CR_PROTOCOL_MINOR UINT8_C(0)
#define CR_ENVELOPE_HEADER_BYTES ((size_t)14)
#define CR_ENVELOPE_CHECKSUM_BYTES ((size_t)4)
#define CR_ENVELOPE_FIXED_OVERHEAD (CR_ENVELOPE_HEADER_BYTES + CR_ENVELOPE_CHECKSUM_BYTES)
#define CR_MAX_ENVELOPE_BYTES ((size_t)(256 * 1024))

typedef enum {
    CR_OK = 0,
    CR_ERR_INVALID_ARGUMENT,
    CR_ERR_TRUNCATED,
    CR_ERR_FRAME_TOO_LARGE,
    CR_ERR_INVALID_MAGIC,
    CR_ERR_INCOMPATIBLE_VERSION,
    CR_ERR_UNKNOWN_MESSAGE_TYPE,
    CR_ERR_UNSUPPORTED_FLAGS,
    CR_ERR_PAYLOAD_LENGTH,
    CR_ERR_CRC_MISMATCH,
    CR_ERR_BUFFER_TOO_SMALL,
    CR_ERR_NUMERIC_OVERFLOW,
    CR_ERR_UNSUPPORTED_MESSAGE,
    CR_ERR_INVALID_PAYLOAD,
    CR_ERR_INVALID_UTF8,
    CR_ERR_STRING_TOO_LONG,
    CR_ERR_TRAILING_BYTES,
} cr_result_t;

typedef enum {
    CR_MESSAGE_SELECT_SESSION = 0x01,
    CR_MESSAGE_SCROLL = 0x02,
    CR_MESSAGE_TERMINAL_KEY = 0x03,
    CR_MESSAGE_PTT_BEGIN = 0x04,
    CR_MESSAGE_PTT_END = 0x05,
    CR_MESSAGE_ACTION_RESULT = 0x06,
    CR_MESSAGE_STATE_SNAPSHOT = 0x07,
    CR_MESSAGE_STATE_DELTA = 0x08,
    CR_MESSAGE_AUDIO_FRAME = 0x09,
    CR_MESSAGE_ASSET_MANIFEST = 0x0a,
    CR_MESSAGE_ASSET_CHUNK = 0x0b,
    CR_MESSAGE_ASSET_ACKNOWLEDGEMENT = 0x0c,
    CR_MESSAGE_DEVICE_INFO = 0x0d,
    CR_MESSAGE_RESYNC_REQUIRED = 0x0e,
} cr_message_type_t;

#endif
